steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/myjobplanner-dinero:$BUILD_ID', '.' ]
  timeout: 360s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/myjobplanner-dinero:$BUILD_ID']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - myjobplanner-cluster
  - myjobplanner-dinero=gcr.io/$PROJECT_ID/myjobplanner-dinero:$BUILD_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=myjobplanner-cluster'
