version: "3.4"
services:
  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    depends_on:
      - db
    command:
      - ./run.sh
  db:
    image: postgres:10.5
    ports:
      - "5432:5432"
