version: "3.4"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    depends_on:
      - db
    command:
      - ./run.sh
    environment:
      - JOBPLANNER_CLIENT_ID=${JOBPLANNER_CLIENT_ID}
      - JOBPLANNER_CLIENT_SECRET=${JOBPLANNER_CLIENT_SECRET}
      - DINERO_CLIENT_ID=${DINERO_CLIENT_ID}
      - DINERO_CLIENT_SECRET=${DINERO_CLIENT_SECRET}
  db:
    image: postgres:10.5
    ports:
      - "5432:5432"
