apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myjobplanner-dinero
  labels:
    app: myjobplanner-dinero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myjobplanner-dinero
  template:
    metadata:
      labels:
        app: myjobplanner-dinero
    spec:
      containers:
        - name: myjobplanner-dinero
          image: gcr.io/myjobplanner-1520708021669/myjobplanner-dinero:645172d7-c9aa-45ba-991e-188e668955a6
          ports:
            - containerPort: 4000
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: HOST
              value: "dinero.myjobplanner.com"
            - name: PORT
              value: "4000"
            - name: SECRET_KEY_BASE
              value: "highlysecretkey"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "jobplanner_dinero_prod"
            - name: DB_HOST
              value: "10.7.224.5"
