apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myjobplanner-dinero
  labels:
    app: myjobplanner-dinero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myjobplanner-dinero
  template:
    metadata:
      labels:
        app: myjobplanner-dinero
    spec:
      containers:
        - name: myjobplanner-dinero
          image: gcr.io/myjobplanner-1520708021669/myjobplanner-dinero:d7ca5b20-2513-4fc4-bcd9-e288efa51fed
          ports:
            - containerPort: 4000
              name: http
          # args: ["foreground"]
          env:
            - name: HOST
              value: "dinero.myjobplanner.com"
            - name: SECRET_KEY_BASE
              value: "highlysecretkey"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "jobplanner_dinero_prod"
            - name: DB_HOST
              value: "10.7.224.5"
