apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myjobplanner-dinero
  labels:
    app: myjobplanner-dinero
spec:
  rules:
  - host: dinero.myjobplanner.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: myjobplanner-dinero-service
          servicePort: 80