apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myjobplanner-dinero
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "myjobplanner-dinero-address"
  labels:
    app: myjobplanner-dinero
spec:
  backend:
    serviceName: myjobplanner-dinero-service
    servicePort: 80